version: '3.8'

services:
  # MongoDB数据库
  mongodb:
    image: mongo:5.0
    container_name: sentiment-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backups:/backups
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    networks:
      - sentiment-network

  # Redis缓存（可选，用于任务队列）
  redis:
    image: redis:6.2-alpine
    container_name: sentiment-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sentiment-network

  # 舆情监控平台应用
  sentiment-monitor:
    build: .
    container_name: sentiment-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017
      - DATABASE_NAME=sentiment_monitor
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - mongodb
      - redis
    networks:
      - sentiment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: sentiment-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - sentiment-monitor
    networks:
      - sentiment-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  sentiment-network:
    driver: bridge
